### PR TITLE
Nytimes page clone

### PR DESCRIPTION
**Pull request by keddo**
### This project is expected to include:
      - Positioning 
      - Applying box model
      - Flex-box and grid layout
      - Clone of Nytimes page

We are kindly requesting for review. 
Thank you.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @keddo and @beyk, great job with this project 👍 Great use of HTML semantics 😃 Let us make our project even better by fixing the comments below:

- Kindly enable stickler by visiting stickler-ci.com
- Kindly remove commented code in ```line 215```
ka3
- Kindly add a link to the NYTimes logo
ka
- Kindly center the ```Theory of inflation```
ka1
- Let us improve the README file, let us add more of our social handles and our email to the author section
- Let us fix 35 errors and warnings returned by the [w3validator](https://validator.w3.org/)
ka2


Going forward, let us improve our commits messages. Example: use ```add``` instead of ```added```, ```fix``` instead of ```fixed```. This [article](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) would help 

Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by keddo** [comment]
### Required change made to the above review
  1. Stickler enabled
  2. Comment removed
  3. Theory of inflation centered
  4. Readme file Improved
  5. Link made to nytimes page
  6. Improve commit message

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @keddo & @beyk! :+1:
- You can now merge to master and I wish you all the very best in your next tasks :first_place_medal:
##
Happy coding :smile:
**[Christian Otieno](https://github.com/christianotieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by keddo** [comment]
Thank you so much.

**Pull request merged**
